Kotik
pupach/lab_hash pull request #2
Opened 2024-05-08 19:29 UTC by pupach

2024-05-08 19:43 UTC, Delton71 commented
Заголовок PR должен содержать ФИО, номер группы, название работы:
Иванов Иван Иванович, Б00-000, Лаба по хешам / Задача A из 2 контеста / ...

2024-05-08 19:49 UTC, Delton71 requested changes
1) Папки `.idea`, `*cmake*` - это бесполезный мусор, захламляющий память коммитов. Срочно добавить их в `.gitignore`
2) Остальные файлы _адекватно_ сгруппировать по папкам. Например: картинки и связанное с ними в `pictures`, тесты в `tests`, хеширование цепочками в `hash_chains`, идеальное в `hash_perfect` и т.д.
3) `hash_cep` - плохой нейминг, лучше `hash_chains`
4) `hash_lin.c` содержит функции открытого хеширования. Так почему же тогда `lin`? Тоже плохой нейминг, замените, например, на `hash_open`

2024-05-08 20:20 UTC, Delton71 commented
![Screenshot from 2024-05-08 23-18-59](https://github.com/pupach/lab_hash/assets/87485621/fd695a73-8800-460f-95a7-2167e983bb20)
На всякий случай, после исправлений ревью надо перезапрашивать (кнопка с круговыми стрелками). Иначе проверки не будет, потому что мы будем считать, что вы еще в процессе.

2024-05-08 21:18 UTC, pupach commented
Левков Александр Александрович Б05-332 Лабраторная работа по Хэшам

2024-05-08 23:19 UTC, Delton71 requested changes
Файлы `data/*.txt` тоже не нужны, потому что:
1) Они отражены на графиках
2) Они занимают много места
3) Пользователь должен быть способен "сделать" их у себя, запустив программу

2024-05-08 23:19 UTC, Delton71 commented on Hash_Perfect.c
> +        HashTablePerfect *arr = (HashTablePerfect *) calloc(capacity, sizeof(HashTablePerfect));
Проверка памяти?

2024-05-08 23:19 UTC, Delton71 commented on Hash_Perfect.c
> +    HashTablePerfect *t = table->arr[hash].val;
__Code style__:
7. Все переменные и функции должны иметь осмысленное имя. Однобуквенные имена разрешается только для счётчиков цикла и для переменных, заданных в условии задачи.

2024-05-08 23:19 UTC, Delton71 commented on Hash_Perfect.c
> +    if(t->arr[hash_new].arr[0] != ElemToFind)
Как работает поиск в `PerfectHash`?

2024-05-08 23:19 UTC, Delton71 commented on Hash_Perfect.c
> +int FindCollision(HashTablePerfect *table, int* val, int len_val);
Она расписана ниже, зачем эта строчка?

2024-05-08 23:19 UTC, Delton71 commented on Hash_Perfect.c
> +    }
Что тут происходит?

2024-05-08 23:19 UTC, Delton71 commented on Hash_Perfect.h
> +}HashTablePerfect;
Не хватает комментариев к переменным, какая за что отвечает
По одним лишь названиям тяжело разобраться

2024-05-08 23:19 UTC, Delton71 commented on Hash_Perfect.h
> +    int consts[2];
Почему 2 элемента, если их 3?

2024-05-08 23:19 UTC, Delton71 commented on Hash_Perfect.c
Добавьте функцию построения таблицы, использующей идеальное хеширование, с НУЛЯ. Сейчас это просто обрывки, а конкретной функции, которая бы на массив чисел выдавала таблицу - нет.

2024-05-08 23:19 UTC, Delton71 commented on find_main.c
> +    InitTable(&hash_qud, size * 2, &MainHashFunc);
Установка `load_factor` должна производиться с помощью функции, желательно, в `InitTable`

2024-05-08 23:19 UTC, Delton71 commented on find_main.c
> +    int *ind_to_find = (int *)calloc(amount_find, sizeof(int));
Проверки выделения памяти?

2024-05-08 23:19 UTC, Delton71 commented on find_main.c
> +    InitTablePerfect(&hash_pefect, (int)sqrt((double) size) * 2, &MainHashFuncPerfect, true);
__Code style__:
8. Переменные должны объявляться по месту использования.

2024-05-08 23:19 UTC, Delton71 commented on find_main.c
> +    }
Это должно быть в функции построения `HashPerfect`

2024-05-08 23:19 UTC, Delton71 commented on find_main.c
> +    InitTablePerfect(&hash_pefect, (int)sqrt((double) size) * 2, &MainHashFuncPerfect, true);
Почему такое `capacity`: `(int)sqrt((double) size) * 2`?

2024-05-08 23:19 UTC, Delton71 commented on find_main.c
> +        GenFirstHashFunc(hash_pefect.arr[i].val, hash_pefect.arr[i].arr, hash_pefect.arr[i].step, 8 * hash_pefect.arr[i].size);
Почему последний аргумент `8 * hash_pefect.arr[i].size`?

2024-05-08 23:19 UTC, Delton71 commented on find_main.h
Что за копипаста .c?

2024-05-08 23:19 UTC, Delton71 commented on hash_chain.c
> +  list->arr = (Elem_listCep *)calloc(sizeof(Elem_listCep), list->capacity + 1);
Проверка?

2024-05-08 23:19 UTC, Delton71 commented on hash_chain.h
> +}Elem_listCep;
Не хватает пояснений к переменным, для чего каждая из них создана

2024-05-08 23:19 UTC, Delton71 commented on hash_chain.c
> +void List_add_Elem_on_O1(List *list, long int val_Elem, int ind_to_ins)
Какой странный нейминг: `List_add_Elem_on_O1`. Что означает?

2024-05-08 23:19 UTC, Delton71 commented on hash_chain.c
> +void List_remove_Elem_on_O1(List *list, int ind_to_ins) {
Какой странный нейминг: `List_remove_Elem_on_O1`. Что означает?

2024-05-08 23:19 UTC, Delton71 commented on hash_open_adress.c
> +    return hash;
Это $\equiv$ `hash | 1`

2024-05-08 23:19 UTC, Delton71 commented on hash_open_adress.c
> +int HashFunc(HashTable *table, ElemToUse ElenToHash)
Почему функция возращает исключительно нечетные значения?
Это должно быть отражено в ее названии

2024-05-08 23:19 UTC, Delton71 commented on hash_open_adress.h
Разделите на несколько файлов с разными методами. А этот .h оформите наподобие:
```c
#include "hash_open_lin.h"
#include "hash_open_quad.h"
#include "hash_open_double.h"
```
Аналогично `hash_open_adress.c` нужно разделить на несколько файлов с разными методами

2024-05-08 23:19 UTC, Delton71 commented on README.md
> +Как видно при меньшем процентном соотношении вставок, two_hash становится по эффективности таким же, как и остальные две(реализация hash_cep просто)
Как будто предложение недописано. Что вы хотели сказать?

2024-05-08 23:19 UTC, Delton71 commented on README.md
> +![Хэш-таблицы, график](graph/hash_1_random_075_without_ceppng.png)
А где выводы в этом пункте?

2024-05-08 23:19 UTC, Delton71 commented on README.md
> +![Хэш-таблицы, график](graph/hash_2_findpng.png)
Вы сами-то видели этот график? Оформите результат не как график, а в виде таблички "время работы/метод"

2024-05-08 23:19 UTC, Delton71 commented on README.md
> +![Хэш-таблицы, график](graph/hash_1_without_ceppng.png)
`load_factor` $\in [1; 5]$. Это как?

2024-05-08 23:59 UTC, VTroyanGolovyan requested changes
Также сделать нормальные подписи к графикам

2024-05-08 23:59 UTC, VTroyanGolovyan commented on hash_open_adress.h
> +}HashTable;
пробел после }

2024-05-08 23:59 UTC, VTroyanGolovyan commented on hash_open_adress.h
> +    int consts[MAX_SIZE_CONSTS];
что это?
назвать так чтоб было понятно

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main_random.c
> +    int (*data)[2] = (int *)calloc(size, sizeof(int[2]));
нет проверок

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main_random.c
> +        if(data[i][0] < 3) {
что такое 3?

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main_random.c
> +        else if(data[i][0] < 6)
что такое 6

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main_random.c
> +            time = DoOneTest(10000 * i, 10000000, 1000, (double) 5 / (double) 12);
ну вот че такое ван тест (назови внятно)
я знаю что есть телефоны ван плас

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main_random.c
> +#define SIZE 100
сайз чего?

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main.c
> +    FILE *stream_Two_Hash   = fopen("Two_Hash.txt",    "w");
нет проверок на файл

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main.c
> +    //DoOneTest(1000, 1000, 10000);
зачем мне закоменченный код?

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main.c
> +    double time_insert[SIZE][4] = {};
что такое 4?
в константы и назвать нормально

2024-05-08 23:59 UTC, VTroyanGolovyan commented on Hash_Perfect.c
> +    }
в отдельную функцию

2024-05-08 23:59 UTC, VTroyanGolovyan commented on Hash_Perfect.h
сгруппируй файлики по папкам

2024-05-08 23:59 UTC, VTroyanGolovyan commented on Hash_Perfect.h
> +bool FindElemTablePerfect(HashTablePerfect *table, ElemToUse ElemToFind);
не хватает const

2024-05-08 23:59 UTC, VTroyanGolovyan commented on graph_ctor (3).py
> +    with open(dataDir + name + ".txt", 'r') as dataFile:
в питоне есть f-строки
f'{dataDir}/{name}.txt'
очень удобно

2024-05-08 23:59 UTC, VTroyanGolovyan commented on graph_ctor (3).py
> +plt.ylabel(units)
size чего
не информативно

2024-05-08 23:59 UTC, VTroyanGolovyan commented on hash_chain.c
> +  list->arr = new_list_arr;
где тут потенциальная утечка памяти?
как исправить?

2024-05-08 23:59 UTC, VTroyanGolovyan commented on hash_chain.c
> +  for(int i = list->capacity; i < new_capacity + 1; i++)
size_t i

2024-05-08 23:59 UTC, VTroyanGolovyan commented on hash_chain.c
> +bool find_Elem_in_list(List *list, int ind_to_find)
const

2024-05-08 23:59 UTC, VTroyanGolovyan commented on hash_chain.c
> +    for (int cur_Elem = 0; cur_Elem < list->capacity; cur_Elem++)
size_t

2024-05-08 23:59 UTC, VTroyanGolovyan commented on hash_chain.h
> +#include <string.h>
после группы инклюдов хотелось бы пустую строку

2024-05-08 23:59 UTC, VTroyanGolovyan commented on hash_open_adress.h
> +bool FindElemTableLin(HashTable *table, ElemToUse ElemToFind);
разбить на файлы
для каждого типа таблицы отдельный
Также хотелось бы видеть DOXYGEN комментарии для всех функций интерфейса

2024-05-08 23:59 UTC, VTroyanGolovyan commented on hash_open_adress.h
> +bool FindElemTableLin(HashTable *table, ElemToUse ElemToFind);
Кроме всего прочего много где не хватает const

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main.c
> +    ret.hash_qud.Insert = clock() - ret.hash_qud.Insert;
Это вообще что?
Названия максимально невнятные

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main.c
> +    for(int i = 0; i < size; i++)
size_t

2024-05-08 23:59 UTC, VTroyanGolovyan commented on main_random.c
> +    hash_two.load_factor = load_factor;
почему бы не делать этов. InitTable

2024-05-08 23:59 UTC, VTroyanGolovyan commented on find_main.h
> +
проверка

2024-05-08 23:59 UTC, VTroyanGolovyan commented on find_main.h
> +    //HashTable hash_two = {};
хлам

2024-05-08 23:59 UTC, VTroyanGolovyan commented on find_main.h
> +    /*ret.hash_two.Insert = clock();
еще хлам

2024-05-08 23:59 UTC, VTroyanGolovyan commented on find_main.h
> +    ret.hash_two.Insert = clock() - ret.hash_two.Insert;
хлам

2024-05-08 23:59 UTC, VTroyanGolovyan commented on find_main.h
> +    for(int i = 0; i < hash_cep.capacity; i++)
size_t

2024-05-08 23:59 UTC, VTroyanGolovyan commented on find_main.h
> +    // free(hash_two.arr);
так это нужно или не нужно чистить?

2024-05-08 23:59 UTC, VTroyanGolovyan commented on find_main.h
> +#define SIZE 5
SIZE - ЧЕГО

2024-05-10 13:11 UTC, pupach commented on hash_chain.c
> +void List_add_Elem_on_O1(List *list, long int val_Elem, int ind_to_ins)
В этой функции я добавляю элесент по индексу, то есть за ассимпотику O(1)

2024-05-10 17:40 UTC, pupach commented on Hash_Perfect.c
> +    }
Что вынести в отдельную функцию? arr не принадлежит таблице де

2024-05-10 17:43 UTC, pupach commented on hash_open_adress.c
> +    return hash;
Эта запись понятнее и легче для дебага

2024-05-10 23:05 UTC, VTroyanGolovyan approved these changes

2024-05-10 23:05 UTC, VTroyanGolovyan commented on README.md
> +![Хэш-таблицы, график](graph/hash_1_random_075_without_ceppng.png)
где вывод?

2025-10-05 17:11 UTC, merged